### ISSUE TITLE
Text is clipped on top after setting lineHeight

### ISSUE THREAD

**Issue by euroboy** [Geri-Borbas/iOS.Blog.UILabel_Typography_Extensions#7]
I'm setting the lineHeight that is equal to font size, but text is clipped on top (see attached screenshot):

`myLabel.font = UIFont.alNile(40, style: .bold)`
`myLabel.lineHeight = 40`
`myLabel.text = "This is a sample text for spacing"`
  
Result:

<img width="280" alt="Screenshot 2023-04-10 at 16 03 47" src="https://user-images.githubusercontent.com/6330272/230906956-c85609ad-9265-4b1a-b3aa-c9667a12b697.png">

**Comment by Geri-Borbas** [comment]
Have you tried with some other (system) font?

**Comment by euroboy** [comment]
Yes, same issue with system font

**Comment by euroboy** [comment]
BTW this only happens on iOS 16.4 and newer, and negative `baselineOffset` is ignored when using with NSParagraphStyle's `maximumLineHeight` and `minimumLineHeight`. On iOS 16.2 works just fine.

**Comment by euroboy** [comment]
UPDATE:

This issue is fixed in iOS 16.6 beta 4, as Release Notes state:

> Known Issues
> 
> Starting in iOS 16.6 a negative value for NSBaselineOffsetAttributeName applied to the full run of an attributedText of a UILabel will return to its pre-16.3 behavior of lowering the text position within the label’s bounds. (106109259)
